# Kafka Deployment with KRaft mode (no Zookeeper needed)
# Uses the official Apache Kafka image
---
# Kafka Service
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: purchase-system
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
      name: broker
  selector:
    app: kafka
---
# Kafka Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: purchase-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:latest
          ports:
            - containerPort: 9092
          env:
            # Broker ID
            - name: KAFKA_BROKER_ID
              value: "1"
            # KRaft mode - Kafka acts as both broker and controller
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_NODE_ID
              value: "1"
            # Controller quorum voters
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@localhost:29093"
            # Listener configuration
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            # Replication settings for single broker
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            # Log directory
            - name: KAFKA_LOG_DIRS
              value: "/tmp/kraft-combined-logs"
            # Cluster ID (required for KRaft)
            - name: CLUSTER_ID
              value: "MkU3OEVBNTcwNTJENDM2Qk"
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "500m"
