# MongoDB Deployment for Purchase System
# Uses a StatefulSet for stable network identity and persistent storage
---
# Headless Service for StatefulSet
# This allows direct pod DNS resolution (mongodb-0.mongodb.purchase-system)
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: purchase-system
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  clusterIP: None  # Headless service
  selector:
    app: mongodb
---
# MongoDB StatefulSet
# StatefulSet provides stable storage and network identity
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: purchase-system
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0
          ports:
            - containerPort: 27017
              name: mongodb
          # Mount persistent volume for data
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          # Resource limits for the container
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
  # Volume claim template for persistent storage
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
