# Kubernetes Namespace
# All resources for this system are deployed in this namespace
# to keep them isolated from other workloads
apiVersion: v1
kind: Namespace
metadata:
  name: purchase-system
  labels:
    app: purchase-system
